GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYzMjFmNzcwOWU5Y2RjYTE2NmEyMzEiLCJpYXQiOjE3MTc3NzU0OTEsImV4cCI6MTcxNzc3OTA5MSwiYXVkIjoieW91cl9hdWRpZW5jZSIsImlzcyI6InRlc3Rkb21haW4uY29tIn0._DSZSygT_QL5ktiwrmHAJ4JA7RR77PGGR4FIRbbBGaM

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"12314test@gmail.com",
    "password":"123test"
}




###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"test213test@gmail.com",
    "password":"123test"
}



###

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYzMjFmNzcwOWU5Y2RjYTE2NmEyMzEiLCJpYXQiOjE3MTc3NzU0NzEsImV4cCI6MTcxODM4MDI3MSwiYXVkIjoieW91cl9hdWRpZW5jZSIsImlzcyI6InRlc3Rkb21haW4uY29tIn0.nskoNj-l_9qFLbYC0HvEziB4U0shwyjh8oUeEQven_g"
}





###

DELETE http://localhost:3000/auth/logout



###
//TEST ROUTE
POST http://localhost:3000/auth/token