GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG5hbWUiLCJpYXQiOjE3MTc3NzQ4NTksImV4cCI6MTcxNzc3NDg3NCwiYXVkIjoiNjY2MzIxZjc3MDllOWNkY2ExNjZhMjMxIiwiaXNzIjoidGVzdGRvbWFpbi5jb20ifQ.Gebip2r8256D_1JkNaeJGDbyp6zSFCAUMm_iGTkykEQ

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"12314test@gmail.com",
    "password":"123test"
}




###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"test213test@gmail.com",
    "password":"123test"
}



###

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjYzMjFmNzcwOWU5Y2RjYTE2NmEyMzEiLCJpYXQiOjE3MTc3NzUyMzIsImV4cCI6MTcxNzc3NTI5MiwiYXVkIjoiNjY2MzIxZjc3MDllOWNkY2ExNjZhMjMxIiwiaXNzIjoidGVzdGRvbWFpbi5jb20ifQ.OG0jMDUlU6EYKBTSqAI-NtFbp-DmM6qF_xHraveLlh8"
}





###

DELETE http://localhost:3000/auth/logout



###
//TEST ROUTE
POST http://localhost:3000/auth/token