GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG5hbWUiLCJpYXQiOjE3MTc3NjY0ODIsImV4cCI6MTcxNzc3MDA4MiwiYXVkIjoiNjY2MmI4ODVhYjQwYjE4Zjk1YjVjMTQzIiwiaXNzIjoidGVzdGRvbWFpbi5jb20ifQ.uIqY5x5_9kET1AhbBDzCivhAZpKg83trjBumhYskq30

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"123test@gmail.com",
    "password":"123test"
}




###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"123test@gmail.com",
    "password":"123test"
}



###

POST http://localhost:3000/auth/refresh-token

###

DELETE http://localhost:3000/auth/logout



###
//TEST ROUTE
POST http://localhost:3000/auth/token