export const USERS_MESSAGES = {
    VALIDATION_ERROR: 'Validation error',
    NAME_IS_REQUIRED: 'Name is required',
    NAME_MUST_BE_A_STRING: 'Name must be a string',
    NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Name length must be from 1 to 100',
    USER_NOT_FOUND: 'User not found',
    EMAIL_IS_REQUIRED: 'Email is required',
    EMAIL_IS_INVALID: 'Email is invalid',
    EMAIL_ALREADY_EXISTS: 'Email already exists',
    PASSWORD_IS_REQUIRED: 'Password is required',
    PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
    PASSWORD_MUST_BE_STRONG: 'Password must contain at least one lowercase letter, one uppercase letter, one number, and one special character',
    PASSWORD_LENGTH: 'Password must be between 6 and 50 characters long',
    CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
    CONFIRM_PASSWORD_MATCH: 'Passwords do not match',
    CONFIRM_PASSWORD_MUST_BE_STRONG: 'Password must contain at least one lowercase letter, one uppercase letter, one number, and one special character',
    CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
    DATE_OF_BIRTH_ISO8601: 'Date of birth must be in ISO 8601 format (YYYY-MM-DD)',
    
};